In [0]:
import numpy as np

In [0]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(my_list)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
#np.zeros(3)
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
#linspace gives evenly space points
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [0]:
#identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
np.random.rand(4)

array([0.57184027, 0.45794521, 0.33115086, 0.54128116])

In [0]:
np.random.randint(1,100,10)

array([36, 30, 97, 20, 39, 15, 85, 60, 74, 21])

In [4]:
#numpy indexing and selection
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
#numpy are different from list because of the ability to broadcast of numpy
#for example
arr[0:5] = 100 # broadcast to 100  for th first 5 elements
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
#indexing 2d array / aka matrix
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
arr_2d[:2,1:] #including everyone up to 2 so from 5, 30 then column one and onwards so 10 to 30

array([[10, 15],
       [25, 30]])

In [26]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [27]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [31]:
#numpy operations
arr = np.arange(0,11)
print(arr-arr)
print(arr+arr)
print(arr+1000)

[0 0 0 0 0 0 0 0 0 0 0]
[ 0  2  4  6  8 10 12 14 16 18 20]
[1000 1001 1002 1003 1004 1005 1006 1007 1008 1009 1010]


In [32]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [33]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])